### ISSUE TITLE
Better UI for Memo

### ISSUE THREAD

**Issue by lubokkanev** [abrkn/mes#1]
A Memo theme for the Stylish extension would be perfect. 

@GitCash send .0005 BCH to @abrkn 

--------- GitCash Tip Bot ---------
Hey @abrkn !
lubokkanev has sent you 0.0005 bch in Bitcoin Cash (~ $ 0.479 )

Follow the link to claim it at

https://gitcash.io/claim/abrkn

  Follow the link and join us!

Bitcoin Cash is an upgrade to the Bitcoin network that restores it&#39;s use as peer to peer digital cash.

Join the rebellion in r/btc
--------- End GitCash Tip Bot ---------

**Comment by abrkn** [comment]
What's that? I'm sadly not a designer

**Comment by abrkn** [comment]
Added by @maplesyrupsucker in #2
