### ISSUE TITLE
The ability to choose between a number of user-created styles 

### ISSUE THREAD

**Issue by kosinusbch** [abrkn/mes#11]
I'm not comfortable enough in JS to make a pull request, but I'm imagining creating a separate folder for stylesheets that users can submit a PR for, and then adding a dropdown somewhere on memo, where the user is able to select their stylesheet of choice. (See 4chan for example)

The stylesheet would then either be loaded from the github, or if its possible with tampermonkey, without adding it to the index.js file, loading it locally.

**Edit**: Actually, just disabled my stylish stylesheet to see how everything looked, seems super slow to kick in. Possible to prioritize MES on pageload?

**Comment by abrkn** [comment]
Yes, I think Tampermonkey has a way to write CSS early. I'll have a look.

**Comment by abrkn** [comment]
See cf182bd8f27d520a5dc8681d65b26aad500e62ea for some improvements to our structure!
