### ISSUE TITLE
Add funds page (new user sign up) should have QR code

### ISSUE THREAD

**Issue by maplesyrupsucker** [abrkn/mes#13]
Need QR code to allow users with small amounts of Bitcoin (BCH) to be added easily to memo on their computer.

**Comment by abrkn** [comment]
Can you provide a screenshot of where this would be? I can inject QRs.

**Comment by maplesyrupsucker** [comment]
It looks like it's available through Dashboard > Set Name on new accounts - which links to 

https://memo.cash/need-funds

![image](https://user-images.githubusercontent.com/3764321/39081222-8dfaf0de-4578-11e8-8de9-87ba6fa132f1.png)


Might be good to have this button added elsewhere with better nomenclature - ie "Add funds" instead of just set name.
